### ISSUE TITLE
MSHTML is deprecated.

### ISSUE THREAD

**Issue by TenTyuteng** [r0x0r/pywebview#1051]
[pywebview] MSHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium

**Comment by sergioalvarezlavin** [comment]
> [pywebview] MSHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium

I am having the same issue. Two computers working with no issues and one showing blank window and the same message in the console. @TenTyuteng did you find any solution?

**Comment by sergioalvarezlavin** [comment]
After investigating the libraries, I found (if I am not mistaken) that the runtimes are included in the library within pywebview, i.e., within the `path=lib\webview\lib\runtimes`.
Am I right? If so, is there any other solution different to downloading the runtime?
I have also tried with 'cef' but I received the following problem "CEF window with uid master does not exist". I saw that it was solved in issue https://github.com/r0x0r/pywebview/issues/968 so I don't understand the problem.

**Comment by r0x0r** [comment]
You need the webview2 runtime. Dlls shipped with _pywebview_ are runtime loaders that communicate with the webview2 runtime.

Have you got cefpython3 installed?

**Comment by sergioalvarezlavin** [comment]
About webview2, my bad! I didn't check it properly!

About "cef", I have cefpython3 installed. However, I checked that the problem is not the "CEF window with uid master does not exist" message. I have tried an online url and it worked despit the message still appears. I think it has something to do with running the server locally, but I am findin the solution.
I' am running a fastApi app in a local port asigned randomly within a thread and trying to show it with pywebview and 'cef' broswer. It is showing blank window no matter what I try. Can you help me? Seems to be something related to some imports in the html files. Here you are the code (simplified) if it helps and some pics afterwards
`
if getattr(sys, 'frozen', False):
    BASE_DIR = os.path.join(os.path.dirname(sys.executable), 'frontend')
else:
    BASE_DIR = os.path.join(os.path.dirname(__file__), 'frontend')

fast_api_app = FastAPI()

fast_api_app.mount(
    "/assets", 
    StaticFiles(directory = os.path.join(BASE_DIR, 'assets')), 
    name="assets"
)

templates = Jinja2Templates(directory=BASE_DIR)

@fast_api_app.get("/", response_class=HTMLResponse)
def home(request: Request):
    return templates.TemplateResponse("index.html", context={"request": request, "name": "PSA"})

@fast_api_app.post('/api/', response_class=JSONResponse)
async def api_post(request: Request):
    #CODE

@fast_api_app.post('/ui/', response_class=JSONResponse)
async def api_post(request: Request):
    #CODE

class Ui():

    def __init__(self, port):

        monitor_info = GetMonitorInfo(MonitorFromPoint((0,0)))
        work_area = monitor_info.get("Work")
        screen_width = int(work_area[2])
        screen_height = int(work_area[3])
        window_width = int(screen_width / 2)
        window_height = int(screen_height)

        window_title = "PSA"
        webview.create_window(
            window_title,
            url='http://127.0.0.1:' + str(port),
            width=window_width,
            height=window_height,
            resizable=True,
            x=screen_width - window_width,
            y=screen_height - window_height,
        )
        webview.start(gui="cef")
                
if __name__ == "__main__":
    
    # Get Port
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(('127.0.0.1', 0))
    port = sock.getsockname()[1]
    sock.close()

    thread_uvicorn = Thread(target=lambda:uvicorn.run(fast_api_app, host='127.0.0.1', port=port))
    thread_uvicorn.daemon = True
    thread_uvicorn.start()
    
    Ui(port)
`

![image](https://github.com/r0x0r/pywebview/assets/99123479/47c031da-497a-4f19-895b-c53e0882e988)
![image](https://github.com/r0x0r/pywebview/assets/99123479/f82a3d23-8e40-4d37-98f5-a49fc658ad5c)

**Comment by sergioalvarezlavin** [comment]
I have found that the issue is caused by 'cef' browser version which has not been udpated in cefpython3 from a long time...
