### ISSUE TITLE
Unable to load DLL 'WebView2Loader.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by Skjolbir** [r0x0r/pywebview#1078]
### Specification
- pywebview version:  4.0.2
- operating system: Windows 10 / Windows 11 (tested on both)
- web renderer: WebView2

### Description  
  
```
[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()  
```

To fix, I had to move WebView2Loader.dll from
.venv\Lib\site-packages\webview\lib\x64\WebView2Loader.dll
to
.venv\Lib\site-packages\webview\lib\WebView2Loader.dll

It seems the issue is solely based on the .dll being within the /x64 folder

### Practicalities

- YES - I am willing to work on this issue myself.

- NO - I am prepared to support this issue financially. (I have no personal or professional financial resources to support with, sorry).

**Comment by r0x0r** [comment]
Could you debug this issue by inspecting what `os.environ['Path'] ` looks like when the exception occurs? Code for dll loading can be found  [here](https://github.com/r0x0r/pywebview/blob/master/webview/platforms/edgechromium.py#L40).

**Comment by Skjolbir** [comment]
`['C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.4.101-hotspot\\bin', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\Calibre2\\', 'C:\\Program Files\\dotnet\\', 'C:\\Users\\opera\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\Program Files\\JetBrains\\PyCharm 2021.1.2\\bin', '', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin', '', 'C:\\Users\\opera\\AppData\\Local\\Programs\\Microsoft VS Code\\bin']`

or for easier reading;

```
C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin     
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\Calibre2\
C:\Program Files\dotnet\
C:\Users\opera\AppData\Local\Microsoft\WindowsApps

C:\Program Files\JetBrains\PyCharm 2021.1.2\bin

C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.3\bin

C:\Users\opera\AppData\Local\Programs\Microsoft VS Code\bin 
```

**Comment by r0x0r** [comment]
The path for dll dirs is not set. Would you verify what does `interop_dll_path(platform)` return on line 41 in edgechromium.py?

**Comment by Skjolbir** [comment]
C:\Users\opera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\lib\x86

**Comment by FI-Mihej** [comment]
@r0x0r @Skjolbir Hi! May I ask why is the reason for just closing this issue? I'm having same issue on two different machines. And it was OK last time I've used Pywebview based code (autumn of 2022)

**Comment by OfekEngelClaroty** [comment]
Having the same issue, [this](https://github.com/r0x0r/pywebview/pull/981) is the pr that introduced the bug. The first path (arm64) just takes precedents so the loading fails on x64 platforms

**Comment by r0x0r** [comment]
@OfekEngelClaroty does changing order of platforms fix the problem? The reason for this change is the old platform detection code did not work for arm64 platform. I left platform choosing to webview2 by adding all the libraries to the path. It worked on my x64 system.

**Comment by kawana77b** [comment]
Hello! Thanks for the nice library!

I can reproduce this phenomenon with the following code when run in Python downloaded from the Microsoft Store (I tested in a Windows 10/Python 3.10/pywebview 4.1 environment).

```python
import webview

window = webview.create_window("google", "https://https://google.com")
webview.start()
```

Similarly, I can reproduce this phenomenon when using `venv` based on Store-distributed Python, which I suspect is the actual cause.
I suspect that the cause is either the `Microsoft.Web.WebView2.Core.dll` specification or the Windows DLL search specification, and I suspect the latter.
When running via the MSIXed and distributed `Python.exe`,
Oddly enough, the internal method of `Microsoft.Web.WebView2.Core.dll` do not appear to search the directory set in `PATH`.
Therefore, I believe that directories such as `lib/x64` are not detected and therefore this error is occurring.
(However, I am not an expert on Windows and WebView2 specifications).

// refercene: Standard search order for packaged apps
https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

This behaviour can be confirmed by Process Monitor (procmon64.exe), which infers that it is not using `Path` for path traversal, as shown in the attached image.

![キャプチャ](https://github.com/r0x0r/pywebview/assets/73901165/ff3c8d1c-a27f-4643-8c9a-58689ba800fb)

Possible workarounds:
I refer to the following link ,
I interpreted that WebView2 currently always searches directories like `lib/runtimes/[arch]/native/WebView2Loader.dll`.

// reference: Files to ship with the app
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Therefore, as a common item that can be applied to the MS Store version,
We might consider changing the configuration of `WebView2Loader.dll` under `webview/lib/` to `lib/runtimes/win-x64/WebView2Loader.dll`.
If we use the MS Store version, we can check that it works correctly in `webview/lib/WebView2Loader.dll`, though,
It seems to work fine with `webview/lib/runtimes/win-x64/native/WebView2Loader.dll`.

In my opinion, using the Mirosoft Store version of Python is a special demand that is controversial,
If there are no problems with this solution, we might be able to consider whether it is necessary.

I am a beginner in GitHub and OSS contributions and do not have enough knowledge to fully validate, refactor and decide if it should be implemented.
If possible, I would be happy if someone could provide validation for the above discussion.
