### ISSUE TITLE
Allow full screen

### ISSUE THREAD

**Issue by armin567ip** [r0x0r/pywebview#1287]
Hi, I need a feature request which is allowing full screen. I mean not actual full screen for the app. for websites like youtube when the video is going to be full screen, i want it to be full screen

**Comment by r0x0r** [comment]
Yeah, this would be a good addition.

**Comment by r0x0r** [comment]
Yeah, I understand.
If you need it asap, you can consider sponsoring this issue.

**Comment by r0x0r** [comment]
I am sorry, but I live in the country where you can get barely a cup of coffee for 5 euros. The rate for custom work is 80e/h.

If this is prohibitively expensive for you, then consider doing it yourself. I think it can be done fairly easy by listening to `fullscreenchange` dom event and then calling `window.toggle_fullscreen()` via js_api.

**Comment by r0x0r** [comment]
I gave this a go and it turned out to be not as straightforward as I thought. The JS API hack did not work and each platform must be tackled separately. It seems to be possible though.

If you want to work on this, here are search keywords to get you on the right track
**wkwebview requestfullscreen**, **webview2 requestfullscreen**, **qtwebengine requestfullscreen**, **gtk webkit requestfullscreen**

ChatGTP might be of help too.
