### ISSUE TITLE
[QUESTION] Is there a way to go back without calling JavaScript using 4.4.1?

### ISSUE THREAD

**Issue by HariZalan** [r0x0r/pywebview#1347]
### Specification
- pywebview version: 4.4.1, because the DEB is very outdated and my environment is externally managed
- operating system: Ubuntu Linux 24.04 Noble Numbat (alpha)
- web renderer: WebKit

### Description

It is mostly a question. I am able to go back/forward by evaluating JavaScript, but some sites (e. g. Google Meet) disabled eval(), what makes this unusable. Is there a better way to do it? I am creating a web browser, so it is quite important to have Back/Forward. In debug mode, there is an option for it,, but if we torture the user with a developer console every browser startup...  I can track the URL, but it is probably not the nicest way.

**Comment by HariZalan** [comment]
Sorry, I just misclicked.

P.S.: I tried to install a newer version, but I was unable to install GTK, and with Qt, it continously crashes.

**Comment by r0x0r** [comment]
`eval` is used internally by `evaluate_js` in order to return the last value in the script. For example, when you run `val = window.evaluate_js("1+1")`, `val` would be 2. I am not entirely sure if it is possible to achieve this without `eval`. It might be, but every platform needs to be investigated separately. 
Another solution could be to implement evalless `evaluate_js` that would just evaluate Javascript without returning a result.

**Comment by HariZalan** [comment]
Thank you for the answer! [My program](https://github.com/HariZalan/Baggins) should be portable, so custom changes does not work, but I still can track the URL and store it in an array.

**Comment by r0x0r** [comment]
I mean that the pywebview api can be modified to support evalless `evaluate_js`.
I have to contemplate this.

**Comment by HariZalan** [comment]
@r0x0r Thank you for your help, now, python3-webview has been upgraded and I can use debug mode without automatic Devtools open. So, it is solved.
