### ISSUE TITLE
[Nuitka] Uncaught ReferenceError: pywebview is not defined

### ISSUE THREAD

**Issue by michaellw** [r0x0r/pywebview#1509]
### Specification
- pywebview version: 5.3.1
- operating system: windows
- web renderer: default

### Description

  The js api works when I run it directly from source, but it doesn't work after compiling with Nuitka.

Using official example from here: [Js Api](https://pywebview.flowrl.com/examples/js_api.html)

![image](https://github.com/user-attachments/assets/1c0928c4-ad85-4e69-996d-8229b554bac0)

**Comment by r0x0r** [comment]
This is likely because of Javascript files refactor introduced in 5.3.
JS files need to be included with the packaged Nuitka app (`webview/js/**/*`). A similar fix was implemented for Pyinstaller already (https://github.com/r0x0r/pywebview/blob/master/webview/__pyinstaller/hook-webview.py), something like this needs to be done for Nuitka as well. I am not familiar with Nuitka, so help is welcomed.

**Comment by michaellw** [comment]
> This is likely because of Javascript files refactor introduced in 5.3. JS files need to be included with the packaged Nuitka app (`webview/js/**/*`). A similar fix was implemented for Pyinstaller already (https://github.com/r0x0r/pywebview/blob/master/webview/__pyinstaller/hook-webview.py), something like this needs to be done for Nuitka as well. I am not familiar with Nuitka, so help is welcomed.

Thanks for the reply, adding the following parameter to the Nuitka command solves the problem.
`--include-data-dir=your/python/Lib/site-packages/webview/js=webview/js`
