### ISSUE TITLE
`pywebview.api` make javascript clog

### ISSUE THREAD

**Issue by qaqFei** [r0x0r/pywebview#1545]
### Specification
- pywebview version:   5.3.2
- operating system: w10
- web renderer: edge webview2

### Description

when call a python function in javascript use pywebview.api,

Even if it's just an empty function in python, i call it when i downkey (4 key),
javascript will clog, fps reduced.

#### Video

https://github.com/user-attachments/assets/474a7e34-6dfb-4420-b86a-b3eaf2006dc1

#### Test Script
```python
import threading

import webview

calFps = '''\
frameCount = 0;
let lastShowTime = performance.now();
let frameShowLabel = document.createElement('p');
frameShowLabel.style.display = 'absolute';
frameShowLabel.style.top = '0';
frameShowLabel.style.left = '0';
const maxFrameTime = 600;

document.body.appendChild(frameShowLabel);
    
function calFps() {
    let nt = performance.now();
    
    if (nt - lastShowTime > maxFrameTime) {
        let useTime = nt - lastShowTime;
        frameShowLabel.innerText = 'JavaScript Run Speed: ' + Math.round(1 / (useTime / frameCount) * 1000);
        lastShowTime = performance.now();
        frameCount = 0;
    }
    
    requestAnimationFrame(calFps);
}

requestAnimationFrame(calFps);
window.addEventListener('keydown', pywebview.api.empty_method);
'''

def test():
    win.evaluate_js(calFps)
    
    while True:
        win.evaluate_js("frameCount++;")
    
class JsApi:
    def empty_method(self, *args):
        pass

win = webview.create_window("Window Clog Test", js_api=JsApi())
threading.Thread(target=test, daemon=True).start()
webview.start()

```

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Your example is broken. empty_method does not get invoked, because it gets passed an event object as an argument. You should change the event handler line to `window.addEventListener('keydown', () => pywebview.api.empty_method());``

I have tested a fixed version and while there is a slight performance drop, I get it as well with a simple `window.addEventListener('keydown', console.log);`. Having said that I have not profiled JS API performance, nor any optimisations have been done on this front. Input is welcomed, if you feel there's a problem.

**Comment by r0x0r** [comment]
There is `_checkValue` function in `webview/js/api.js` that checks the return value of jsapi function call. It uses setInterval that is invoked every millisecond. My guess is this interval is the performance bottleneck. Setting an interval to a larger value would be a straightforward way to check.
Other than that, getting rid of the interval would be a better resolution, but I am not 100% sure if this is possible for every platform. This logic was written many years ago and is same for every platform. I haven't touched it since then.

**Comment by qaqFei** [comment]
![image](https://github.com/user-attachments/assets/6d1238c9-2466-48e2-8130-87be6c1f0a05)
i looked this code, we may create a callback in javascript, when function return, call the callback and give result

**Comment by qaqFei** [comment]
i try try

**Comment by qaqFei** [comment]
i tested a fix version, but this problem is still exists.

**Comment by qaqFei** [comment]
emm, i think the bug cause by:
![image](https://github.com/user-attachments/assets/762cafc4-3cf7-4ead-9917-b2de371c2fad)

this image is my application error window, 
i raise a error when lock create,
![image](https://github.com/user-attachments/assets/a4096856-e7ad-4754-b751-be69c05700f9)

when i run js codes to render a frame, it will create a lock,
but this bug in single-threaded application maybe not happen.

my application use a thread to render frame, so the fps is very very low,
but in October or September, the bug was not happen, i think it maybe affected by version,
but i test other version, the bug is also exists.

**Comment by qaqFei** [comment]
we maybe can create a flag, 
if the flag is enable, we change wait method.

when i use time.sleep and a flag object to wait this, 
it isnot clog other python thread.

**Comment by qaqFei** [comment]
so, i will create a pull request to fix the bug,
it will offer a function to enable a flag,
when we use a thread to render frame,
we should call the new functoin,
the new functoin will change Event and Lock and other threading object work method.

**Comment by qaqFei** [comment]
and the bug isnot happening in javascript,
it only clog python.

**Comment by qaqFei** [comment]
oh, I was wrong,
when i delete this code in my application:
![image](https://github.com/user-attachments/assets/deb2a41a-d723-40e3-8114-6a014a4aefc1)
The problem then does not exist.

sorry very much.
