### ISSUE TITLE
Pywebview cutting out html/js features

### ISSUE THREAD

**Issue by ironman5366** [r0x0r/pywebview#23]
Hi. I've been working on a production level project for a while now involving pywebview. The client and I recently noticed that one of the html files displayed is lacking certain features when displayed in pywebiew. The features are present when it's opened in any browser. I'm uploading screenshots and the html files in hope that it can be fixed. I tested this error by opening the html files with a python shell command copied from the quickstart, so it's not other code in my program. 
[htmlfiles.zip](https://github.com/r0x0r/pywebview/files/109203/htmlfiles.zip)

![screenshot 27](https://cloud.githubusercontent.com/assets/10326155/12665470/eef2f30e-c605-11e5-8c7e-6029db28f85e.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/10326155/12665473/f2d39bb8-c605-11e5-9cdb-963f93f7e9ea.png)

**Comment by r0x0r** [comment]
Windows 10 uses IE11 as a renderer. Could you open your page in IE11 and see if it is rendered correctly? 
Here are instructions on how to launch IE on Windows 10. http://m.windowscentral.com/how-find-internet-explorer-windows-10-if-you-really-need-it

**Comment by ironman5366** [comment]
The page doesn't work in IE I believe. We've tried uninstalling IE, but still doesnt work.

**Comment by r0x0r** [comment]
Win32 API of Windows 10 can only use IE as a web view renderer. For Spartan rendering .NET must be used and as far as I know Microsoft does not have any plans adding support for Spartan in Win32. Pywebview does not have support for .NET currently, but as this is a serious issue, I will add on a to-do list.

If your issue is related to IE support, please close it. I will open a new ticket for adding .NET support.

**Comment by ironman5366** [comment]
Sure thing. Thanks for the help
