### ISSUE TITLE
Javascript API stops working after reloading the page

### ISSUE THREAD

**Issue by mikahama** [r0x0r/pywebview#238]
### Specification
- Platform: mac
- Version: 2.0.3

### Description
On Mac, when I create the window, the API calls work as expected. If, however, I reload the page, by navigating to the same url again with webview.load_url, by running location.reload(); with javascript or just by right clicking on the page in debug mode and selecting reload, the API stops working. Inspector shows ReferenceError: Can't find variable: pywebview.

<img width="912" alt="captura de pantalla 2018-06-18 a las 19 17 26" src="https://user-images.githubusercontent.com/1543680/41548809-a4b5b930-732c-11e8-95c5-394b20d733f4.png">

**Comment by r0x0r** [comment]
JS API and CSS changes currently do not persist after a page reload. This should definitely be remedied.  If you wish to give it a go, PRs are welcomed.

**Comment by jrr8** [comment]
I found a partial workaround for this issue that will allow you to mimic a redirect. You may be able to modify this to work for a refresh as well.

Before I had a button that triggered a redirect from '/' to '/home', and the pywebview variable disappeared on the '/home' page, as you've noted.

The fix was instead of redirecting from '/' to 'home', I would AJAX fetch the content of '/home' from '/' and then call document.write() on the '/' page with the response from '/home'. This keeps the location at '/' but allows me to display the content of '/home' while still having access to the pywebview variable. Hope that helps.

**Comment by r0x0r** [comment]
I pushed a macOS fix to the `fix-jsapi-reload` branch. 
@mikahama @jrr8 please test if the fix works for you.

Other platforms need to be addressed too.

**Comment by r0x0r** [comment]
PR here 
https://github.com/r0x0r/pywebview/pull/248

**Comment by r0x0r** [comment]
QT / GTK do not have this problem.
Windows preserves the API on url navigation, but not on refresh (eg. location.reload()). I cannot think of a solution for this, but at least it is documented here.

**Comment by r0x0r** [comment]
Found a Windows solution. PR is here https://github.com/r0x0r/pywebview/pull/249
