### ISSUE TITLE
Play vedio( YouTube) can't fullscreen

### ISSUE THREAD

**Issue by Tx-hub** [r0x0r/pywebview#472]
### Specification
- pywebview version: 3.2
- platform / version: Mac OS 10.14.6

### Description  
  
  Play a Vedic can't fullscreen. the bottom right-hand corne side my browser can't support fullscreen,and I can't fullscreen any h5 Vedio. I am a beginner, I wish you can help me, thx:)
<img width="346" alt="image" src="https://user-images.githubusercontent.com/57650001/74582885-41a66c00-4ffc-11ea-8e0a-8caffb15a82d.png">

**Comment by r0x0r** [comment]
I think there is no simple way to implement this. 
Full-screen is of course possible on the Python side, but  plugging it into Javascript ecosystem is problematic. Rewriting native implementations with custom ones is always an option (as it is done with window.alert), but in case of requestFullscreen it has to be replaced on every DOM element. It might be done using prototypes, but I cannot say for sure at this point.

**Comment by Tx-hub** [comment]
So there is no easy way to achieve it? If it's my own website, I can use js API, but there's no way for a website like YouTube. Btw, I can't use the full screen in pywebview example. Is this a python for Mac bug? There is no response whether it is a double-click or a single click. thx your help,

**Comment by r0x0r** [comment]
There was a bug in the todos app that prevented fullscreen, which I now fixed in master.
I am afraid requestFullscreen cannot be easily supported. The only way I can think of would be inject Javascript code using `evaluate_js` that would re-implement fullscreen functionality for video.

If you manage to get it working, please report back.
