### ISSUE TITLE
Question about mixing it with wxpython

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#475]
Is it viable to mix a pywebview window with wxpython so we can, for instance, have a system tray launcher for windows? Or are there any caveats/problems?

Also, I supose (i haven't checked it yet) that we could extend the base code to add things like native menus to the main window, right? Or that is a no go?

¡Thanks!

**Comment by r0x0r** [comment]
I have not investigated embedding pywebview into wxpython. I guess it is
possible, but I cannot see an easy way to do it.

As for features you are after, requests for both come up quite often. I
have nothing against into implementing this functionality, but chances I
will tackle them anytime soon are slim. If you wish to give it a go, pleas
let me know, so that we could figure out the API syntax first.
