### ISSUE TITLE
Webview doesn't load when I import pystray

### ISSUE THREAD

**Issue by alexwohlbruck** [r0x0r/pywebview#486]
- pywebview version: 3.2
- platform / version: Windows 10

For some reason when I try to use this library with [pystray](https://pypi.org/project/pystray/) (a library that creates a system tray icon), I get this strange runtime error. I am pulling my hair out trying to get these two modules to work together, but I don't know what this error message is coming from. Only when I import both of the libraries and try to create a new window.

```
import webview
import pystray
	
window = webview.create_window('Woah dude!', html='<h1>Woah dude!<h1>')
webview.start()
```

```
Unhandled Exception: Python.Runtime.PythonException: ArgumentError : argument 1: <class 'OverflowError'>: int too long to convert
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Anybody else getting this on their machines? How can I even begin to debug this?

**Comment by r0x0r** [comment]
First of all, this is the first time I heard about pystray. Second, systray feature has been requested many times, so the best course would be to implement into pywebview imo. However, using this library sounds like a viable choice as well.
This error message is not very informative, so it is hard to say whether the problem is in pystray or pywebview. pystray is implemented with pywin32 and pywebview with winforms, so my guess either one sets something that conflicts with the other one. As for how to debug it, I would set breakpoints early in the code of both libraries and see how far it can go. If breakpoint cannot be hit (as in the case of code run in Windows threads), replace breakpoint with print statements and see what is displayed and what is not.
Hopefully this is of help to you.

**Comment by AlexCovizzi** [comment]
Got the same error, for me it happens only when I package the application using PyInstaller.
Following @r0x0r suggestion I traced back the error to this 2 lines in `winforms.py`:
```
handle = windll.kernel32.GetModuleHandleW(None)
icon_handle = windll.shell32.ExtractIconW(handle, sys.executable, 0)
```
After trying some things I was able to solve it by implementing the solution suggested here: [Link to Stackoverflow](https://stackoverflow.com/questions/17033733/call-to-getmodulehandle-on-kernel32-using-python-c-types)
I'll open a PR with the change

**Comment by r0x0r** [comment]
@AlexCovizzi @alexwohlbruck care to add a barebone example that would demonstrate a minimal use of pywebview with pystray?

**Comment by alexwohlbruck** [comment]
@r0x0r I don't think i ever got this to work. I have been using the Eel library and it's working well for me!

**Comment by AlexCovizzi** [comment]
@r0x0r I open a pull request with a simple example https://github.com/r0x0r/pywebview/pull/670
