### ISSUE TITLE
Performance issues on Raspberry Pi 4

### ISSUE THREAD

**Issue by cyberplant** [r0x0r/pywebview#523]
### Specification
- pywebview version: 3.2
- platform / version: raspbian 10 (ARMv7l 32 bits)

### Description  
  
Hello!

I have an electron app that I would like to migrate to pywebview, and I'm very happy so far, but I'm having much slower performance on pywebview compared to chromium on the same RPi4.

I would like to investigate this, if it's something pywebview can change, using different flags for the rendering engines (to mimic what chromium has configured for the RPi), or if I should report this to upstream. I tested GTK and QT bindings, with different results, but with problems on both.

GTK ones work better in general, but I have one video on the app and it shows at 1 or 2 FPS. (the same video plays perfectly on chromium). QT works a bit faster but I need to double-click on links most of the time and no video at all.

Any ideas?
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Would you check what Chromium version is used both with GTK and QT? A wild guess is that it is using an ancient Chromium that results in poor performance. Also how did you install dependencies, via `apt` or `pip`?

**Comment by cyberplant** [comment]
I'm not sure how to get the real version, so I got the user agent on both cases:
With GTK:
Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

With QT:
Mozilla/5.0 (X11; Linux) AppleWebKit/602.1 (KHTML, like Gecko) Qt/5.11.3 Version/9.0 Safari/602.1

On the chromium itself on the OS:
Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36

GTK bindings came with the OS (I guess) as I installed pywebview using pip and it didn't install much. With QT it installed a lot of things (with pip as well, and I think I also installed some things on the OS manually according to your instructions).

**Comment by r0x0r** [comment]
I do not have access to Raspberry Pi, so cannot check it for myself. I have got the same WebKit version on my desktop system (Intel Nuc based) and videos play with no problems. 
Sorry no clue about this one. Maybe somebody else can chime in.

**Comment by tnagels** [comment]
I have similar problems. On RPI my jpg-stream works perfectly in Chromium, but in pywebview, I only get 1-2 frames per second which flash into view and then go. So in effect I get flickering images.

I'm willing to provide you with an RPI if that helps resolve the issue.

**Comment by r0x0r** [comment]
@tnagels I can take a look if you provide me with a RPI. Send me a message at roman at flowrl.com

**Comment by tnagels** [comment]
@r0x0r I just sent you an email!

**Comment by r0x0r** [comment]
Thanks to @tnagels I got an opportunity to investigate this. No results yet, but the status of current investigations are

1) GTK shows a warning about lack of hardware acceleration, which I suppose the reason of poor performance.  Upgrading GTK dependencies would probably the best course of action. I vaguely remember installing GTK dependencies outside of the default repos on Raspbian. There might be an instruction for that somewhere among the issues.
2) Managed to install PyQT5, but no luck with webkit/webengine dependencies. QTWebKit seems to be easier to install on Raspbian.

**Comment by r0x0r** [comment]
Ok more findings:

- It seems the only way to get decent web performance on RPI is via Chromium renderer. All other renderers seem to be inherently slow and this performance problem is not caused by pywebview per se.
- There are two ways to get Chromium: via QTWebEngine and cefpython3 
- There is not ARM build for cefpython3. The ticket for ARM support has been open for four years already https://github.com/cztomczak/cefpython/issues/267, with no progress in sight.  Then there is this guide on building CEF on RPI, so it seems doable https://medium.com/@tejohnso/chromium-embedded-framework-on-the-raspberry-pi-b91b01f51c9
- QTWebEngine is another choice. Unfortunately I could not find a prebuilt package, apart from this https://github.com/koendv/qt5-opengl-raspberrypi (could not get it to work). Building it from scratch is likely the only viable choice. There are plenty of guides on how to do it though, e.g. https://wiki.qt.io/RaspberryPiWithWebEngine or https://ottycodes.wordpress.com/2019/02/21/cross-compiling-qt5-12-for-raspberry-pi3/ 

I am not very good at or keen on building Linux packages, so maybe somebody else could give it a try and report results back here.

**Comment by tnagels** [comment]
Any chance of trying the Ubuntu build for the RPI4? There is one which is supported by the RPI Imager. Maybe that has different/more packages.

**Comment by r0x0r** [comment]
Yeah, I will give it a try.

**Comment by r0x0r** [comment]
@tnagels Good news. I got adequate video performance with Ubuntu for RPI4. 480p at 30fps, on par with performance of Chromium.

I used this command for installing dependencies
```
sudo apt install python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtwebchannel libqt5webkit5-dev```

**Comment by tnagels** [comment]
@r0x0r that is indeed good news! I will give this a try as soon as I have some time on my hands.
