### ISSUE TITLE
GTK JS bridge truncate function calls to 1000 chars

### ISSUE THREAD

**Issue by ikhmyz** [r0x0r/pywebview#554]
webkit get_title() is not suitable for use as bridge as it truncates function calls to 1000 chars.

```
window.pywebview.api.myfunction('0'.repeat(1001))
```

platforms/gtk.py
```
def on_title_change(self, webview, title):
    title = webview.get_title()
    print(len(title))  # >>> 1000 chars
    try:
        js_data = json.loads(title)
        ...

Traceback (most recent call last):
  File "/home/noname/dev/ANTIDETECT/py/octobrowser-client/venv/lib/python3.6/site-packages/webview/platforms/gtk.py", line 192, in on_title_change
    js_data = json.loads(title)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 71 (char 70)

(currently this error is not catching, I removed try except to see it)
```

**Comment by r0x0r** [comment]
Yes, it is not. This is, though, the best I could find.

The problem is that the native JS bridge of WebKitGTK has not been implemented. It could be apparently patched with C code, but I am not touching that. At least this was the situation the last time I checked. If you find a better solution, feel free to contribute.

**Comment by r0x0r** [comment]
Actually double checking this, screw my comment above. The C patch issue was with returning a Javascript value, which has been fixed in newer WebKitGTK versions.
Getting Python exposed to Javascript would require a web extension, which are apparently not supported for Python. Using a C wrapper could fix this. Here is an example 
https://github.com/aperezdc/webkit2gtk-python-webextension-example <https://github.com/aperezdc/webkit2gtk-python-webextension-example>

This is slightly beyond my expertise, nor I am not too motivated on investigating this. Contributions welcomed.
