### ISSUE TITLE
Local webserver 404s with query string in URL- 3.3 regression

### ISSUE THREAD

**Issue by Jon-Work** [r0x0r/pywebview#567]
### Specification
- pywebview version:  3.3.1
- platform / version: Linux - Ubuntu 18.04

### Description  
  
  With PyWebView 3.2, I can open a local file with URL parameters, e.g.:

    window = webview.create_window('Test', 'ui/index.html?foo=bar')
    webview.start(gui='gtk')

  That doesn't work in 3.3.1, I get a 404 error saying the file was not found.

  Removing the query string makes it work again.

  I guess that maybe the newly-rewritten webserver doesn't remove query strings before trying to find the file on disk?

### Practicalities

- NO I am not likely to have time to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes, seems related to the new web server.
@astronouth7303 Could you take a look?

**Comment by astronouth7303** [comment]
Yes, but not by the mechanism you think.

`examples/http_server.py` works when you add a query string.

However, you do not have `http_server` in `window.start()`, so it is not starting a server, so the string is treated as a file path. Specifically, it is [made absolute and then run through `pathlib.Path.as_uri()`](https://github.com/r0x0r/pywebview/blob/d362a6ee53a289ee438ae0e2b1eae4b97c4d1227/webview/serving.py#L111).

The old behavior was to just [append it to the base path](https://github.com/astronouth7303/pywebview/blob/a27f3ab86dbaa17e91c7a137b2d62c48c7864ed8/webview/util.py#L60), which could cause problems with some file names.

I guess it's @r0x0r's decision if paths as `str` should be allowed to have query strings. (Paths as `Path` objects should not be allowed to have query strings.)

Workaround: I _think_ if you add `http_server=True` to `webview.start()`, it'll work. (That'll cause it to actually start a webserver and actually serve it as HTTP, instead of transforming it into a `file:` URL.) Of course, this changes the context of your app and that can have _weird_ ripple effects.

**Comment by astronouth7303** [comment]
(For the record, I think there's a certain amount of purity of just treating the string as a path.)

**Comment by Jon-Work** [comment]
Note that:

* The official file URI spec doesn't allow file URIs to contain a query string or fragment - https://tools.ietf.org/html/rfc8089
* But the official web browser URI spec DOES allow file URIs to contain query strings and/or fragments - https://url.spec.whatwg.org/#concept-basic-url-parser

I think that pywebview should be following the web browser spec when it converts the path to a URI.  I agree that just treating the string as a path is pure and nice.  But perhaps window.start could have some extra arguments for me to specify the query string parameters & a fragment to be added to the File URI before it gets passed to the web browser.  (See urllib.parse.urlencode for an existing API for encoding a query string).

**Comment by astronouth7303** [comment]
Note that this specific example (`ui/index.html?foo=bar`) isn't obviously a URL--it could be treated as a URL or a relative path.

That said, `file:ui/index.html?foo=bar` is a relative URL, and should trigger the URL-parsing logic. (Although maybe it can do a better job of handling relative paths?)

**Comment by Jon-Work** [comment]
You're correct that `file:ui/index.html?foo=bar` triggers the URL-parsing logic, and from code inspection it looks like it should handle relative paths just fine.  Unfortunately, it also throws away the query string.  Maybe fixing that to pass the query string through would be the best fix?

**Comment by astronouth7303** [comment]
OH, yeah it would. That's not great.

The problem with how it currently handles relative paths is that if anything else in-process changes the current directory, the server will break.

If it's passed a file URL, preserving other parts of the URL would be a good idea.

**Comment by astronouth7303** [comment]
still a bug, bot
