### ISSUE TITLE
how to save/where to find all the images shown in webview? 

### ISSUE THREAD

**Issue by the-oaks** [r0x0r/pywebview#621]
### Specification
- pywebview version: 3.3.5
- platform / version: windows

### Description  
  
  is there a folder that stores all the cached image? if so, may I ask where to find them? if not, is there a way we can systematically store them? thanks 
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
a) This is highly renderer specific. 
b) I have no idea where each renderer stores its cache. At least MSHTML shares its cache with Internet Explorer, other renderers are probably different.
c) There has been interest in providing cache/cookie control / incognito mode, so this issue is worth investigating.

**Comment by kakksanthusa** [comment]
You Can search img elements and get its src property using evaluate js
