### ISSUE TITLE
Keyboard focus on MacOS

### ISSUE THREAD

**Issue by diegojromerolopez** [r0x0r/pywebview#66]
Hello r0x0r, when trying to type in an input the focus is on the terminal that called the Python application but mouse works perfectly. I tried reading the docs thinking I maybe needed an specific parameter or setting but I'm not sure which one.

My application is a embebed Django web application and this is the [main file that create the webview](https://github.com/diegojromerolopez/django-trello-stats/blob/desktop/src/desktop_app_manage.py). [Here is the call to webview constructor](https://github.com/diegojromerolopez/django-trello-stats/blob/desktop/src/desktop_app_manage.py#L177)

What I'm doing wrong? Any help is appreciated.

Thank you.

**Comment by r0x0r** [comment]
Hey, I don't quite follow what the problem is. What is exactly the problem and what platform are you using?

**Comment by diegojromerolopez** [comment]
I launch the application from the terminal and when writing in an input field the text appears in the terminal. So I assumed that there was a problem with the focus.

OS is OSX El Capitan 10.11.6.

**Comment by r0x0r** [comment]
I cannot reproduce it. I have tested it flask_app by adding an input box to examples/flask_app/gui/index.html

**Comment by diegojromerolopez** [comment]
Hi r0x0r I've made a pull request with a small Django application that suffers of this problem. There is information about running this app in the pull request.

Thank you.

**Comment by r0x0r** [comment]
This issue seems to occur only under virtualenv. Could you verify that this is the case on your machine?
I don't have much experience in virtualenv. No idea where to look for the problem.

**Comment by diegojromerolopez** [comment]
I'm going to try to use another alternative method to virtualenv and see what happens.

**Comment by r0x0r** [comment]
Any update?

**Comment by diegojromerolopez** [comment]
I've tried using docker and no luck so far.

I'm going to use some packaging tool like py2app next week and see how it goes.

**Comment by r0x0r** [comment]
The problem is caused by the Python interpreter supplied by virtualenv. It acts as a command line application and does not properly register a GUI window with OSX.
I managed to fix the issue by copying the original python executable over your_virtual_env/bin/python.
The virtualenv documentation also describes another way to use a virtualenv with an alternative python interpreter.
https://virtualenv.pypa.io/en/stable/userguide/#using-virtualenv-without-bin-python

**Comment by ericmjl** [comment]
I see. It must be the same with my Conda installation in #68. Thanks for finding the cause, @r0x0r!

**Comment by diegojromerolopez** [comment]
Thank you @r0x0r I'm going to check it!

**Comment by r0x0r** [comment]
Updated README with this info.

**Comment by r0x0r** [comment]
This seems to be related as well https://github.com/gldnspud/virtualenv-pythonw-osx/

**Comment by diegojromerolopez** [comment]
Confirming that with https://github.com/gldnspud/virtualenv-pythonw-osx pywebview works 100%. Thanks!

**Comment by cateee** [comment]
BTW, I think this issue should remain open, until it will be solved (possibly by some dependencies). And in README, I don't think the title is appropriate. VirtualEnv is a cause, but I think the title should have the real issue: e.g. "Lack of keyboard events on macos/cocoa".

Reading StackOverflow, it is a common problem (in objc), so I assume it is due to some subtle change in pyobjc, or just pywebview not keeping up the new flags, interfaces, etc. I've tried many "_solutions_", but without luck, and pyobjc examples are designed in a very different way.

In any case, forcing QT solves the problem, allowing me to use virtual environment and python 3.6. (which is important for me, because of backend code, and using to processes it is not so clean)

**Comment by psytron** [comment]
+1 Still experiencing this issue. Python 3.7.4. All keyboard input is captured by terminal window, will not show up in pywebview.

**Comment by shakfu** [comment]
I confirm I had the same issue trying to run the todos example out of a virtualenv on mac os 10.14.6 (home brewed Python 3.7.5): text was consistently routed to the terminal (even when I detached the process with 'python start.py &'

**Comment by lwerdna** [comment]
I have the same issue running the todos example.
OS: MacOS 10.15 Catalina
Python: 3.7.4 installed in pyenv

**Comment by danvenn** [comment]
I agree that this should be reopened. Doesn't seem like an appropriate fix to manually replace the python executable when using virtual environments.

**Comment by r0x0r** [comment]
@danvenn what check do you propose?

**Comment by danvenn** [comment]
@r0x0r I couldn't tell you the best way, but one way might be to check if an OSX user is inside a venv, then restart using pythonw / python framework. Looks like there has been some discussion and fixes in the matplotlib repo about this issue. [(see here)](https://github.com/matplotlib/matplotlib/pull/11850)

Rough code idea:
```
import sys
if sys.platform == "darwin":         #If OSX
    if sys.prefix != sys.base_prefix: # and if inside a venv
        ## warn user ##
        ## check if using framework/ pythonw##
        ##restart with framework## -> os.execv(  ..... , sys.argv) 
```
