### ISSUE TITLE
window does not open when the python script is spawned using NodeJS on windows server 2016

### ISSUE THREAD

**Issue by MANIRATHA** [r0x0r/pywebview#682]
### Description
The pywebview window when spawned using NodeJS does not open on windows server 2016. The script seems to be running but the window is no where to be seen. I am using the window to serve a flask route.
Does pywebview support server operating systems?

**Comment by r0x0r** [comment]
I have not tested it personally, but I do not see any reason why it should not work. pywebview relies on Windows Forms, which is shipped with .NET. I would start by checking which vesion of .NET you have installed and whether any additional dependencies are needed.

**Comment by peter23** [comment]
I'm not sure about Edge, but IE in Windows Server has restricted set of allowed sites.
Pywebview is seen as "about:security_python.exe" and is not allowed to run.
(instead of python.exe there can be name of your executable if you use PyInstaller or something)
If you run `webview.start` with `debug=True` you will see that.

You can manually add it to list of allowed sites with the following code:
```
def python_to_allowed(esc, name):
	regpath = r'Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\{}Domains\{}'.format('Esc' if esc else '', name)
	winreg.CreateKey(winreg.HKEY_CURRENT_USER, regpath)
	regkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, regpath, 0, winreg.KEY_WRITE)
	winreg.SetValueEx(regkey, 'about', 0, winreg.REG_DWORD, 2)
	winreg.CloseKey(regkey)

python_to_allowed(False, 'security_python.exe')
python_to_allowed(True, 'security_python.exe')
```
