### ISSUE TITLE
Provide JavaScript ↔ Python bridge to pywebview

### ISSUE THREAD

**Issue by aplicacionamedida** [r0x0r/pywebview#83]
It's possible to create a bridge between the webview and python without depending on sockets. The problem of starting a server on windows is that the firewall can block the application or show a security warning, including when I start the server only on localhost.
http://stackoverflow.com/questions/40492842/how-to-suppress-the-windows-security-alert-for-windows-firewall

Very probably this bridge between a webview and the python interpreter is much more efficient because it doesnt use the HTTP protocol, and it hasn't the before mentioned problem:

   http://askubuntu.com/questions/97430/connect-webkit-webview-form-to-a-python-callback
   http://pysnippet.blogspot.com.es/2010/01/calling-python-from-javascript-in-pyqts.html
   http://stackoverflow.com/questions/5885290/how-to-call-javascript-function-from-pyqt

**Comment by r0x0r** [comment]
It is a cool feature, but looks like a great deal of work. It would require careful planning to get a uniform experience across different platforms. 
[PyJs](https://github.com/pyjs/pyjs) implements something similar and covers Linux and Windows. I haven't explored it in details, but it seems like their implementation could be used as a starting point.

**Comment by shivaprsdv** [comment]
If I understand correctly, the OP is talking about communicating between JS
& Python without using web-server frameworks. If that is so, half of the work
needed has just been done by implementing `evaluate_js()` on all platforms,
not just QT.

Implementing the reverse bridge indeed looks challenging, still it's worth a try.
I am editing the title to make it less specific.

**Comment by r0x0r** [comment]
Different platforms use different approaches, which make it non-trivial to come up with a single cross-platform solution. To sum it up
- Windows use an `window.external` Javascript object that can be assigned a Python object
- In OSX you can expose any ObjC object to Javascript. Here is an example how it is done https://stackoverflow.com/questions/2288582/embedded-webkit-script-callbacks-how/2293305#2293305
- QT does the same. 
- GTK is problematic, as the options are limited to manipulating `window.status`, or `document.title` and redirecting a page to a custom protocol URL and trapping a corresponding event in Python.

The greatest common factor is having a global object `window.external` or another appropriate name that would correspond to a user created object in Python. Maybe GTK can be tackled by creating a similar object using `evaluate_js` that would map function calls to AJAX calls to a custom protocol URL.

Anyhow, seems like a lot of work, but should be doable and the more I think about it, the more I like this idea.

**Comment by shivaprsdv** [comment]
We can do this. My suggestions:

* Let's go with the `window.external` object on all platforms.
* Keep it simple: let this object have a single method named `invoke` (or some
thing similar) with a single string as argument. We can hook this method to a
Python callback which will accept the string. The callback could be added as
a parameter to `create_window`. To pass complex objects, user can serialise
them as JSON and parse them back in Python.
* It'd be simpler to use `evaluate_js` and `window.status` on GTK instead of
custom URLs.

This would give total control to the user. We can always extend the `external`
object in the future if we need.

**Comment by r0x0r** [comment]
I have been investigating how to do it in WinForms and it does not look good so far. The problem is with making Python objects visible to COM. I have raised an issue with pythonnet here https://github.com/pythonnet/pythonnet/issues/567

Regarding the public interface, I am inclining to introducing a `window.pywebview` object for having everything pywebview related under it. The scripting object would be `pywebview.api` and it would not have any predefined methods, but would point to the passed Python object.

I will check with PyJs, if their codebase is of any help.

**Comment by shivaprsdv** [comment]
Hm, I don't quite get it. Questions:

1. What exactly is the role `pywebview.api`, to represent a Python object? So that
we can access its properties and methods directly in JavaScript?
2. Is the user supposed to provide this object as an argument to `create_window`?

If this is so, this would require some work, especially on GTK and (apparently) on
Winforms as well. Can't it be a simple function-passing-string, as `evaluate_js`?

**Comment by r0x0r** [comment]
1. Yes. It would be a Python object exposed in Javascript. At least In
Winforms, the implementation would be no different to your proposal,
provided it can be implemented at all.
2. Either a parameter to create_window or a separate function,
set_js_api(object) or something like that.

**Comment by shivaprsdv** [comment]
Okay then, but wouldn't `window.pywebview` suffice? Why do we need an `api` sub-object?

**Comment by r0x0r** [comment]
There might be need for more pywebview related JS variables in the future, so it is better to keep everything under one global object. Just preparing for the future.

I managed to get WinForms working, but the methods must be defined in advance, so that leaves out with a single Invoke method. However, I think it will be possible to mock user provided API in Javascript, so that mocked methods would use Invoke internally. Currently Invoke uses the `(message, param)` signature, where message is a string and param is jsonified data. 

It is also possible to return a value from the Invoke method, which is nice. Other platforms should be checked for a return value possibility as well. 

I will push my code, as soon as I tidy it up a bit.

**Comment by shivaprsdv** [comment]
I have experimented with it on Cocoa and Gtk (my original approach), seems
like it would work as you propose with minor changes. Cocoa supports return
value directly, and Gtk works with some workarounds.

**Comment by r0x0r** [comment]
I have pushed a proof-of-concept Windows implementation to the `scripting-object` branch. Some notes

- The API object is via the `webview.set_api` function. Using a function allows changing the object during the run-time. I am not entirely convinced this is a right approach. Maybe it should be made a parameter to `create_window` instead
- The JS glue code is located at `js/api.js`. It can probably be used for all the platforms, minus the window.external line. 
- The invoke function is called `call`. Could not use `Invoke` or `invoke` for some reason, it probably has to with clashing with C#'s own `Invoke` method.
- The function accepts two parameters (both strings): a function name and JSONified params. Params can be left out. If params are provided, pywebview converts JSON to a dict.
- If the function is not found, it fails silently and returns undefined. An exception might be a good idea.

**Comment by shivaprsdv** [comment]
I have had a look, some quick suggestions/questions :

* Setting the API object via the functions allows flexibility, but the backend is
currently not as flexible. Every time a user sets it, the `pywebview.api` object
should be cleared and created anew. If this is done properly, then a function
is a better interface than a `create_window` parameter.
* The names `set_api` and `api_object` are kind of obscure; would be better
to call them `set_js_api` and `js_api_object` explicitly.
* `api.js` can be reused completely; we only need to create `window.external`
on other platforms with the `call` method, so that the pathway is uniform.
* It is better to throw the function-not-found-exception in the JS context. On
the Python side the current logger warning would suffice.
* I see that you are setting the Python `api` object as a class variable. Instead
it could be made an attribute of the JSBridge class itself; a `js_bridge` object
of this class may be added to `BrowserView.instance`. This would be a better
encapsulation, it especially benefits the multi-window feature (each window
could get a separate `api` object).

**Comment by r0x0r** [comment]
Good suggestions. I have pushed changes to the branch 
- Let's keep it this way for now.
- I have changed the function to `set_js_api(api_instance)`. The name should be clear enough.
- I would like to keep the `window` namespace as pure as possible, but if this gets the job done, it is ok with me
- Good point. Done.

One more thing to consider. 
- API's functions must be asynchronous in order not to block execution. Wrapping the functions inside the promise syntax could be the way to handle asynchronicity. The implementation must be ES5 compatible and the options are either roll out own implementation (here is how http://modernjavascript.blogspot.fi/2013/08/promisesa-understanding-by-doing.html) or take a minimal library/polyfill into use. For example, http://microjs.com/#promise

**Comment by shivaprsdv** [comment]
All fine! I have pushed the commit for Cocoa. I have _copied_ both `set_js_api`
and `JSBridge.call` method logic to init.py; both can be reused. Please check
it out, you could rewrite Winforms to import them from there.

And about the last suggestion about promises, I say we can look into it later,
after implementing the feature on all platforms. We might then only need to
make changes to the `api.js` interface.

**Comment by shivaprsdv** [comment]
Done necessary modifications to avoid polluting the `window` namespace on
Cocoa.

**Comment by shivaprsdv** [comment]
I have pushed the commit for GTK. It's super hacky using `window.status`, but
it works. 🤓 Details in comments and commit message.

**Comment by r0x0r** [comment]
Both PyQ4 and PyQT5 are implemented and pushed. Things to do before the merge
- Promise interface
- Proper example
- Tests
- Documentation

I will start looking into picking a suitable promise library

**Comment by r0x0r** [comment]
https://github.com/getify/native-promise-only
This polyfill does the job nicely. Small and is as close as to ES6 promises as possible.

Promises do not solve the problem completely. As long-running code is executed on the UI thread, it freezes the UI during the execution. Semaphors cannot be used here, as UI blocks as long as the semaphore is acquired. I have tried only with Cocoa, but I suspect the problems persists on all the platforms.

I have pushed the current progress.

**Comment by r0x0r** [comment]
I have pushed a non-blocking version of JS bridge functions. It uses a combination of polling and recursive setTimeouts, which is enough to warrant the hacky label, but it does the job. Suggestions how this can be improved are most welcomed.

**Comment by r0x0r** [comment]
Made OSX implementation thread safeish. Now set_js_api is executed only when DOM is ready. GTK seems to suffer from the same problem. 
Another problem found with OSX is that when window is closed during JS function execution, the program hangs.

**Comment by shivaprsdv** [comment]
The current PyQT5 implementation does not work on latest versions of Qt5 (>5.4
or so). A new interface called [QWebChannel](http://doc.qt.io/qt-5/qwebchannel.html) seems to have replaced the role of `addToJavaScriptWindowObject`.
(https://forum.qt.io/topic/56091/addtojavascriptwindowobject-with-qt-5-5)

**Comment by r0x0r** [comment]
Works with 5.5.1 and Python 3.5. What version were you testing with?

**Comment by shivaprsdv** [comment]
5.7.1 on Python 2.7. I reckon it has nothing to do with the Python version, see
the traceback:
![screen shot 2017-12-01 at 11 33 09 am](https://user-images.githubusercontent.com/18247990/33470049-56e9d41c-d68c-11e7-83c4-8a755b71d388.png)

**Comment by r0x0r** [comment]
I gave the QT >5.5 implementation a go, but could not get it working for some reason. Another realisation I made from the QT efforts is that it is better to get rid of set_js_api and make it a parameter to create_window to avoid race conditions. Having several semaphors acquiring and releasing each other can get messy pretty quickly.
I will push work in progress code shortly.

**Comment by r0x0r** [comment]
Pushed. The code is a bit of a mess at the moment after many implementation iterations and I haven't tested whether I had broken <QT5.5 and QT4 implementations, but if someone could give  the >QT5.5 API a go, it would be greatly appreciated.

**Comment by shivaprsdv** [comment]
Negative. It does not produce anymore Python exceptions, but the buttons in
the example are simply unresponsive. With a bit of digging around I found that
`window.external` is still undefined despite the changes.

I had given it a go some time ago, but the QWebChannel interface did not seem
straightforward like `addToJavaScriptWindowObject`. In fact it was pretty much
daunting that I finally dropped it for then. 🤷‍♂️

**Comment by r0x0r** [comment]
Yeah this is the case with the `window.external` being undefined. All is not lost though. These are examples of how QWebChannel is registered, so I assume it works at least for some people :)
 https://www.google.fi/search?q=filetype%3Apy+QWebChannel+registerobject&oq=filetype%3Apy+QWebChannel+registerobject
Upon examining some examples I could not figure that it is done differently, but the next step would be reducing one of these examples to bare bones and getting it to work on its own.

**Comment by r0x0r** [comment]
Good news. I've managed to get it working. The trick was to load an additional JS library `qrc:///qtwebchannel/qwebchannel.js`  and call Python functions using 
```
new QWebChannel(qt.webChannelTransport, function(channel)
    {
        channel.objects.external.python_func()   
    });
```
Why they made it so complicated is beyond me.

I will clean up the code and push fixed version whenever I get time.

**Comment by shivaprsdv** [comment]
Need to update the `create_window` signature on other platforms as well. 👍

**Comment by r0x0r** [comment]
Refactored all the platforms, added tests and fixed concurrency issues. The only thing that fails at the moment is `is_running` check on GTK when running `test_js_bridge`. I have commented it out to make the tests pass. @shivaprsdv could you take a look at it?

**Comment by r0x0r** [comment]
Please see the latest commit https://github.com/r0x0r/pywebview/commit/5f90f844892dfd0047aec1f32b1f0ac45525194e. I uncommented the code that made the test fail, so please give it one more try.

**Comment by shivaprsdv** [comment]
Okay, I think it was some race condition that didn't show up in my system; but it
did when I used Python 3. I have pushed a fix and the build is passing.

**Comment by r0x0r** [comment]
We are good to go. I have created a pull request. Will wait for comments for a couple of days before merging.

**Comment by r0x0r** [comment]
Merged with master, closing this issue now.
