### ISSUE TITLE
`beforeunload` event not works

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [r0x0r/pywebview#882]
### Specification
- pywebview version: 3.6.3
- operating system: Win10 19042.1586
- web renderer: edgeChromium

### Description  
  
In normal browser environment, such as Chrome, we add a listener on the `beforeunload` event to give user an alert dialog, tips them to save their working.
However, it seems not works on pywebview, the webview was closed directly without check the `beforeunload` event. I found the `window.events.closing` api, but it works on python-side where more difficultly to check the javascript-side state, what's more, when I tried to called `window.evaluate_js` the process will blocking.
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
According to MDN `beforeunload` is unreliable and there are no guarantees that it would work at all.
Calling evaluate_js in `closing` resulting in a blocking is clearly a bug. The cause is async evaluating of Javascript and js_semaphore that blocks until JS result is obtained. I am not entirely sure what happens during closing  process and whether it is possible to execute async Javascript at all, but it you want to take a look relevant places to look are winforms.py line 286 and edgechromium.py `evaluate_js` function. 
Waiting on the js_result semaphore in the closing code may be a solution.
