### ISSUE TITLE
Unable to handle and manage special keyboard combinations on MacOS.

### ISSUE THREAD

**Issue by jczic** [r0x0r/pywebview#996]
### Specification
- pywebview version: 3.7.2
- operating system: M1, MacOS Ventura 13.0
- web renderer: Cocoa

### Description  
  
Unable to handle (and/or cancel the propagation of) special keyboard combinations with the MacOS **Cmd/Meta** key like **Meta+Z** or **Meta+Q**.
These events are directly and simply captured by the system but not by the PyWebView UI window.

Example: In javascript "**keydown**", "**keypress**" or "**keyup**" does not catch the combination and the program exits directly or the main window receive signal to close.

(I have integrated the CodeMirror javascript editor and the undo or redo methods are therefore impossible and quit the program).
  
### Practicalities

- [NO] : I am willing to work on this issue myself.

- [NO] : I am prepared to support this issue financially.

**Comment by ecpost** [comment]
I ran into a related (but different) problem with other keys like Home and End, and tracked it down to the `performKeyEquivalent_()` method in cocoa.py.  I also ran into the same problem as you with keys like Meta+C.  Some comments about both types of problems:
-- Our Meta+Z/Meta+C problem is happening because `performKeyEquivalent_()` is intercepting those to translate them into the built-in undo/copy functionality.  The method also returns True to tell the caller that they were already handled, which is why they never make it to the javascript "keydown" event.
-- My Home/End problem is because `performKeyEquivalent_()` only returns False (allowing it to reach the JS event) in certain scenarios.  Specifically, for Meta-key combinations that are NOT intercepted for built-in functionality, and for a hard-coded list of cursor keys (that happens to be missing Home and End).  This is because the method has `return True` at the end, which at first glance looks like a bug.  But I only say "looks like" because this was intentionally added at some point (5f8827537b5ce722960f574209a5631de4e71950), and because of the fact that the list of permitted cursor keys was added to circumvent this same problem for those other keys (ceb647f8bbe7769b031415abfa1e9a4018eb364b).  Although I can't tell from the commit comments if that was thought through all the way or just done as a quick fix.
-- Meta+Q is a special case, unfortunately.  Removing the quit-app-and-return-True code from `performKeyEquivalent_()` will still result in the program exiting (I'm assuming you don't want that) as long as it returns False.  But (just) returning True, although that prevents the standard MacOS behavior of quitting, does not allow the event to reach javascript, since it ends right there.  In other words, there's no way, from `performKeyEquivalent_()`, to tell the app both not to quit, and to allow the Meta+Q event to reach javascript.  Maybe there's another AppKit method/hook besides performKeyEquivalent that could help with this?

Like I said, I don't know if there was reason `return True` was added at the and, but assuming for the moment that it was a mistake to do that...  I suggest switching that back to `return False` and removing the cursor keys workaround at the top.  (I'm happy to submit a PR for that if @r0x0r agrees.)

But that doesn't take care of the other 2 issues.  It seems like the code to intercept Meta+Z/Meta+C/etc. would be better if it existed later in the event handling sequence, and only ran if the javascript code didn't do something like `event.preventDefault()`.  But I don't know if/where that kind of hook exists.  I can look in to that if @r0x0r doesn't have any issues with that or other suggestions.  Another idea would be to add some kind of option to pywebview to circumvent this behavior.  (A flag to have it always return False, or a way to override that code.)  But that's a little weird since this is MacOS specific.  (Not sure if other environments have similar issues.)

BTW, I'm currently working around the first 2 problems by monkey-patching the class at runtime to just return False, since I don't need the other built-in functionality.  For example, running something like this before calling any pywebview code:

    import WebKit, AppKit
    class Wrapper(WebKit.WKWebView):
        def performKeyEquivalent_(self, theEvent):
            return False
    BrowserView.WebKitHost.performKeyEquivalent_ = Wrapper.performKeyEquivalent_

And because of the 3rd issue, Meta+Q still quits, which in my case I want.

Actually, I do want Meta+W to close the window, so I actually do this:

        def performKeyEquivalent_(self, theEvent):
            if theEvent.type() == AppKit.NSKeyDown and theEvent.modifierFlags() & AppKit.NSCommandKeyMask and self.window().firstResponder() and theEvent.keyCode() == 13:
                self.window().performClose_(theEvent)
                return True
            return False

**Comment by jczic** [comment]
Hi and thank you very much @ecpost  !
Well, this is a tricky subject.
The same problem exists for CTRL too (on mac) and for the moment, I try to block Meta+Z and try to capture just the keyup of CTRL+Z / CTRL+SHIFT+Z.
I'll learn more about that...

**Comment by r0x0r** [comment]
@ecpost yes, you are right.  Returning False would be a better option. Would you make a PR?

**Comment by ecpost** [comment]
Ok thanks, done.  #999 

@jczic , this will take care of the Ctrl-Z/Ctrl-Shift-Z examples you just mentioned, but the handlers for the standard actions like copying still take precedence.  I'm not sure if there's a good/clean way to address that.  But I'll probably look in to it more at some point...

**Comment by ecpost** [comment]
@r0x0r Regarding the other issue/request, do you happen to recall, when this was originally written, if there was a preference/reason to use `performKeyEquivalent_` in favor of `keyDown_`?  I ask because it looks like if I take the code in performKeyEquivalent_ and put it in a keyDown_ override instead (with a couple small tweaks, like calling the super instead of returning False), everything works exactly as jczic and I were hoping.  Specifically, all key events make it to javascript (before the pywebview override), and calling preventDefault on the javascript event prevents keyDown_ from being called.  It even works for Meta+Q.  I've tried it out with `<input>` and `<textarea>` tags in the html, and all of the cut/copy/paste/select-all/undo/quit/close key combinations (moved to keyDown_) still work properly, with or without a javascript event handler, unless preventDefault is called on the event in the javascript.

If you don't think performKeyEquivalent_ (specifically) was critical for anything, I can update the PR with this change.  (If it was actually important for something, let me know.  Maybe whatever it was can still be handled somehow along with what I'm proposing.)

**Comment by r0x0r** [comment]
@ecpost I have no memory of why `performKeyEquivalent_` is used and my Cocoa knowledge is patchy at best. `keyDown_` is fine by me, if it performs better.

**Comment by ecpost** [comment]
@r0x0r Thanks, it's switched.

**Comment by jczic** [comment]
By the way, it works very well now :)
👍🏻

**Comment by jczic** [comment]
Thank you again @ecpost  & @r0x0r, my mini-IDE with CodeMirror works perfectly with PyWebView :)
I had small problems to manage several windows created at the beginning then posted in time but we manage very well and I thank you both again (I made a small sponsorship also to @r0x0r).

Here is an idea of my software running on MacOS arm64, MacOS Intel x86_64 and Windows 64 bits with PyInstaller :
https://github.com/jczic/ESP32-MPY-Jama

**Comment by ecpost** [comment]
Awesome, glad to here it!  Hope your project does well!
